/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { Quantity } from './quantity';
import type { TimePeriod } from './timePeriod';

/**
 * Complements the description of an element (for instance a product) through video, pictures...
 */
export type AttachmentAllOf = {
  /** a business characterization of the purpose of the attachment, for example logo, instructionManual, contractCopy */
  attachmentType?: string;
  /** The actual contents of the attachment object, if embedded, encoded as base64 */
  content?: string;
  /** A narrative text describing the content of the attachment */
  description?: string;
  /** a technical characterization of the attachment content format using IETF Mime Types */
  mimeType?: string;
  /** The name of the attachment */
  name?: string;
  size?: Quantity;
  /** Uniform Resource Locator, is a web page address (a subset of URI) */
  url?: string;
  validFor?: TimePeriod;
};
