/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { Price } from './price';
import type { PriceAlteration } from './priceAlteration';
import type { ProductOfferingPriceRef } from './productOfferingPriceRef';

/**
 * An amount, usually of money, that represents the actual price paid by the customer for this item. May represent the total price of the shopping cart or the total of the cart item depending on the relation
 */
export type CartPriceAllOf = {
  /** A narrative that explains in detail the semantics of this cart or cart item price. */
  description?: string;
  /** A short descriptive name such as "Subscription price". */
  name?: string;
  price?: Price;
  priceAlteration?: PriceAlteration[];
  /** A category that describes the price, such as recurring, discount, allowance, penalty, and so forth */
  priceType?: string;
  productOfferingPrice?: ProductOfferingPriceRef;
  /** Could be month, week... */
  recurringChargePeriod?: string;
  /** Could be minutes, GB... */
  unitOfMeasure?: string;
};
