/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { TimePeriod } from './timePeriod';

/**
 * Indicates the contact medium that could be used to contact the party.
 */
export type ContactMediumMVOAllOf = {
  /** Type of the contact medium to qualifiy it like pro email / personal email. This is not used to define the contact medium used. */
  contactType?: string;
  /** Identifier for this contact medium. */
  id?: string;
  /** If true, indicates that is the preferred contact medium */
  preferred?: boolean;
  validFor?: TimePeriod;
};
