/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { EntityRef } from './entityRef';
import type { TimePeriod } from './timePeriod';

/**
 * A uni-directionmal relationship from this entity to a target entity instance
 */
export interface EntityRelationshipMVO {
  /** When sub-classing, this defines the super-class */
  '@baseType'?: string;
  '@referredType'?: string;
  /** A URI to a JSON-Schema file that defines additional attributes and relationships */
  '@schemaLocation'?: string;
  '@type'?: string;
  associationSpec?: EntityRef;
  href?: string;
  id?: string;
  name?: string;
  /** Type of relationship such as migration, substitution, dependency, exclusivity */
  relationshipType?: string;
  /** The association role for this entity */
  role?: string;
  validFor?: TimePeriod;
}
