/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { CharacteristicFVO } from './characteristicFVO';
import type { EventFVOAllOfEvent } from './eventFVOAllOfEvent';
import type { RelatedPartyRefOrPartyRoleRefFVO } from './relatedPartyRefOrPartyRoleRefFVO';
import type { EntityRefFVO } from './entityRefFVO';

/**
 * event with common attributes.
 */
export type EventFVOAllOf = {
  analyticCharacteristic?: CharacteristicFVO[];
  /** The correlation id for this event. */
  correlationId?: string;
  /** An explnatory of the event. */
  description?: string;
  /** The domain of the event. */
  domain?: string;
  /** The event linked to the involved resource object */
  event: EventFVOAllOfEvent;
  /** The identifier of the notification. */
  eventId: string;
  /** Time of the event occurrence. */
  eventTime: string;
  /** The type of the notification. */
  eventType: string;
  /** Hyperlink reference */
  href?: string;
  /** unique identifier */
  id?: string;
  /** A priority. */
  priority?: string;
  relatedParty?: RelatedPartyRefOrPartyRoleRefFVO[];
  reportingSystem?: EntityRefFVO;
  source?: EntityRefFVO;
  /** The time the event occurred. */
  timeOccurred?: string;
  /** The title of the event. */
  title?: string;
};
