/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */

/**
 * Base Extensible schema for use in TMForum Open-APIs - When used for in a schema it means that the Entity described by the schema  MUST be extended with the @type
 */
export interface ExtensibleFVO {
  /** When sub-classing, this defines the super-class */
  '@baseType'?: string;
  /** A URI to a JSON-Schema file that defines additional attributes and relationships */
  '@schemaLocation'?: string;
  /** When sub-classing, this defines the sub-class Extensible name */
  '@type': string;
}
