/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { StandardIdentifier } from './standardIdentifier';
import type { ExternalIdentifier } from './externalIdentifier';
import type { GeographicLocationRefOrValue } from './geographicLocationRefOrValue';
import type { GeographicSubAddress } from './geographicSubAddress';

/**
 * Structured textual way of describing how to find a Property in an urban area (country properties are often defined differently).
Note : Address corresponds to SID UrbanPropertyAddress
 */
export type GeographicAddressAllOf = {
  /** City that the address is in */
  city?: string;
  /** Country that the address is in */
  country?: string;
  /** Country codes are short alphabetic or numeric geographical codes (geocodes) developed to represent countries and dependent areas, for use in data processing and communications. Several different systems have been developed to do this. The term country code frequently refers to ISO 3166-1 alpha-2 or international dialing codes, the E.164 country calling codes. */
  countryCode?: StandardIdentifier[];
  externalIdentifier?: ExternalIdentifier[];
  /** Classification of the address, e.g., residential, industrial  */
  geographicAddressType?: string;
  geographicLocation?: GeographicLocationRefOrValue;
  geographicSubAddress?: GeographicSubAddress[];
  /** An area of defined or undefined boundaries within a local authority or other legislatively defined area, usually rural or semi rural in nature. [ANZLIC-STREET], or a suburb, a bounded locality within a city, town or shire principally of urban character [ANZLICSTREET] */
  locality?: string;
  /** descriptor for a postal delivery area, used to speed and simplify the delivery of mail (also know as zipcode) */
  postcode?: string;
  /** the State or Province that the address is in */
  stateOrProvince?: string;
  /** Name of the street or other street type */
  streetName?: string;
  /** Number identifying a specific property on a public street. It may be combined with streetNrLast for ranged addresses */
  streetNr?: string;
  /** Last number in a range of street numbers allocated to a property */
  streetNrLast?: string;
  /** Last street number suffix for a ranged address */
  streetNrLastSuffix?: string;
  /** the first street number suffix */
  streetNrSuffix?: string;
  /** A modifier denoting a relative direction */
  streetSuffix?: string;
  /** alley, avenue, boulevard, brae, crescent, drive, highway, lane, terrace, parade, place, tarn, way, wharf  */
  streetType?: string;
};
