/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { GeographicLocationFVOAllOfType } from './geographicLocationFVOAllOfType';

/**
 * A GeographicLocation is a pure-virtual super-class to the GeoJSON-aligned geometries of Point (addresses and locations), MultiPoint, LineString (streets, highways and boundaries), MultiLineString and Polygon (countries, provinces, tracts of land). Use the @type attribute to specify which of these is being specified by the geometry attribute.
 */
export type GeographicLocationFVOAllOf = {
  /** The name of the GeoJSON structure used in the geometry attribute */
  '@type': GeographicLocationFVOAllOfType;
  /** A bounding box array that contains the geometry. The axes order follows the axes order of the geometry */
  bbox?: number[];
  /** An URI used to access to the geographic location resource */
  href?: string;
  /** Unique identifier of the geographic location */
  id?: string;
};
