/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { Disability } from './disability';
import type { IndividualIdentificationFVO } from './individualIdentificationFVO';
import type { LanguageAbility } from './languageAbility';
import type { OtherNameIndividual } from './otherNameIndividual';
import type { Skill } from './skill';
import type { IndividualStateType } from './individualStateType';

/**
 * Individual represents a single human being (a man, woman or child). The individual can be a customer, an employee or any other person that the organization needs to store information about.
 */
export type IndividualFVOAllOf = {
  /** e.g. Baron, Graf, Earl */
  aristocraticTitle?: string;
  /** Birth date */
  birthDate?: string;
  /** Country where the individual was born */
  countryOfBirth?: string;
  /** Date of death */
  deathDate?: string;
  /** List of disabilities suffered by the individual */
  disability?: Disability[];
  /** Contains the non-chosen or inherited name. Also known as last name in the Western context */
  familyName?: string;
  /** Family name prefix */
  familyNamePrefix?: string;
  /** A fully formatted name in one string with all of its pieces in their proper place and all of the necessary punctuation. Useful for specific contexts (Chinese, Japanese, Korean) */
  formattedName?: string;
  /** Gender */
  gender?: string;
  /** e.g.. Sr, Jr, III (the third) */
  generation?: string;
  /** First name of the individual */
  givenName?: string;
  /** List of official identifications issued to the individual, such as passport, driving licence, social security number */
  individualIdentification?: IndividualIdentificationFVO[];
  /** List of national languages known by the individual */
  languageAbility?: LanguageAbility[];
  /** Legal name or birth name (name one has for official purposes) */
  legalName?: string;
  /** Temporary current location of the individual (may be used if the individual has approved its sharing) */
  location?: string;
  /** Marital status (married, divorced, widow ...) */
  maritalStatus?: string;
  /** Middles name or initial */
  middleName?: string;
  /** Full name flatten (first, middle, and last names) - this is the name that is expected to be presented in reference data types such as PartyRef, RelatedParty, etc. that refer to Individual */
  name?: string;
  /** Nationality */
  nationality?: string;
  /** List of other names by which this individual is known */
  otherName?: OtherNameIndividual[];
  /** Reference to the place where the individual was born */
  placeOfBirth?: string;
  /** Contains the chosen name by which the individual prefers to be addressed. Note: This name may be a name other than a given name, such as a nickname */
  preferredGivenName?: string;
  /** List of skills exhibited by the individual */
  skill?: Skill[];
  status?: IndividualStateType;
  /** Useful for titles (aristocratic, social,...) Pr, Dr, Sir, ... */
  title?: string;
};
