/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { AttachmentRefOrValue } from './attachmentRefOrValue';
import type { Characteristic } from './characteristic';
import type { Expression } from './expression';
import type { EntityRelationship } from './entityRelationship';
import type { EntityRef } from './entityRef';
import type { RelatedPartyRefOrPartyRoleRef } from './relatedPartyRefOrPartyRoleRef';
import type { TimePeriod } from './timePeriod';

/**
 * An Intent instance is the formal description of all expectations including requirements, goals, and constraints given to a technical system
 */
export type IntentAllOf = {
  /** Attachments that may be of relevance to this intent, such as picture, document, media */
  attachment?: AttachmentRefOrValue[];
  characteristic?: Characteristic[];
  /** A string used to give a context to the intent */
  context?: string;
  /** Date and time of the creation of this REST resource */
  creationDate?: string;
  /** The description of the intent. */
  description?: string;
  expression?: Expression;
  /** A list of intents related to this intent */
  intentRelationship?: EntityRelationship[];
  intentSpecification?: EntityRef;
  /** isBundle determines whether an intent represents a single intent (false), or a bundle of intents(true). */
  isBundle?: boolean;
  /** Date and time of the last update of this REST resource */
  lastUpdate?: string;
  /** Used to indicate the current lifecycle status of this intent */
  lifecycleStatus?: string;
  /** The name of the intent. */
  name?: string;
  /** Can be used by intent owner to prioritize intents in an intent management system */
  priority?: string;
  relatedParty?: RelatedPartyRefOrPartyRoleRef[];
  /** A date time( DateTime). The date that the entity status changed to the current one */
  statusChangeDate?: string;
  validFor?: TimePeriod;
  /** A field that identifies the specific version of an instance of an intent. */
  version?: string;
};
