/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { TimePeriod } from './timePeriod';
import type { OrganizationChildRelationshipMVO } from './organizationChildRelationshipMVO';
import type { OrganizationIdentificationMVO } from './organizationIdentificationMVO';
import type { OrganizationParentRelationshipMVO } from './organizationParentRelationshipMVO';
import type { OtherNameOrganizationMVO } from './otherNameOrganizationMVO';
import type { OrganizationStateType } from './organizationStateType';

/**
 * Organization represents a group of people identified by shared interests or purpose. Examples include business, department and enterprise. Because of the complex nature of many businesses, both organizations and organization units are represented by the same data.
 */
export type OrganizationMVOAllOf = {
  existsDuring?: TimePeriod;
  /** If value is true, the organization is the head office */
  isHeadOffice?: boolean;
  /** If value is true, the organization is a legal entity known by a national referential. */
  isLegalEntity?: boolean;
  /** Organization name (department name for example) */
  name?: string;
  /** Type of the name : Co, Inc, Ltd, etc. */
  nameType?: string;
  /** List of organizations that are contained within this organization. For example if this organization is the Legal Department, the child organizations might include Claims, Courts, Contracts */
  organizationChildRelationship?: OrganizationChildRelationshipMVO[];
  /** List of official identifiers given to the organization, for example company number in the registry of companies */
  organizationIdentification?: OrganizationIdentificationMVO[];
  organizationParentRelationship?: OrganizationParentRelationshipMVO;
  /** Type of Organization (company, department...) */
  organizationType?: string;
  /** List of additional names by which the organization is known */
  otherName?: OtherNameOrganizationMVO[];
  status?: OrganizationStateType;
  /** Name that the organization (unit) trades under */
  tradingName?: string;
};
