/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { TimePeriod } from './timePeriod';

/**
 * Keeps track of other names, for example the old name of a woman before marriage or an artist name.
 */
export interface OtherNameIndividual {
  /** e.g. Baron, Graf, Earl, etc. */
  aristocraticTitle?: string;
  /** Contains the non-chosen or inherited name. Also known as last name in the Western context */
  familyName?: string;
  /** Family name prefix */
  familyNamePrefix?: string;
  /** . A fully formatted name in one string with all of its pieces in their proper place and all of the necessary punctuation. Useful for specific contexts (Chinese, Japanese, Korean, etc.) */
  formattedName?: string;
  /** Full name flatten (first, middle, and last names) */
  fullName?: string;
  /** e.g. Sr, Jr, etc. */
  generation?: string;
  /** First name */
  givenName?: string;
  /** Legal name or birth name (name one has for official purposes) */
  legalName?: string;
  /** Middle name or initial */
  middleName?: string;
  /** Contains the chosen name by which the person prefers to be addressed. Note: This name may be a name other than a given name, such as a nickname */
  preferredGivenName?: string;
  /** Use for titles (aristrocatic, social, ...): Pr, Dr, Sir,.... */
  title?: string;
  validFor?: TimePeriod;
}
