/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { AccountRefFVO } from './accountRefFVO';
import type { AgreementRefFVO } from './agreementRefFVO';
import type { CharacteristicFVO } from './characteristicFVO';
import type { ContactMediumFVO } from './contactMediumFVO';
import type { CreditProfileFVO } from './creditProfileFVO';
import type { PartyRefFVO } from './partyRefFVO';
import type { PartyRoleSpecificationRefFVO } from './partyRoleSpecificationRefFVO';
import type { PaymentMethodRefFVO } from './paymentMethodRefFVO';
import type { RelatedPartyOrPartyRoleFVO } from './relatedPartyOrPartyRoleFVO';
import type { TimePeriod } from './timePeriod';

/**
 * The part played by a party in a given context.
 */
export type PartyRoleFVOAllOf = {
  account?: AccountRefFVO[];
  agreement?: AgreementRefFVO[];
  /** Describes the characteristic of a party role. */
  characteristic?: CharacteristicFVO[];
  contactMedium?: ContactMediumFVO[];
  creditProfile?: CreditProfileFVO[];
  /** A description of the PartyRole. */
  description?: string;
  engagedParty: PartyRefFVO;
  /** A word, term, or phrase by which the PartyRole is known and distinguished from other PartyRoles. It's the name of the PartyRole unique entity. */
  name: string;
  partyRoleSpecification?: PartyRoleSpecificationRefFVO;
  paymentMethod?: PaymentMethodRefFVO[];
  relatedParty?: RelatedPartyOrPartyRoleFVO[];
  /** Role played by the engagedParty in this context. As role is defined by partyRoleSpecification, this role attribute can be used to precise the role defined by partyRoleSpecification, or it can be used to define the role in case there is no partyRoleSpecification. */
  role?: string;
  /** Used to track the lifecycle status of the party role. */
  status?: string;
  /** A string providing an explanation on the value of the status lifecycle. For instance if the status is Rejected, statusReason will provide the reason for rejection. */
  statusReason?: string;
  validFor?: TimePeriod;
};
