/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { ContactMediumFVO } from './contactMediumFVO';
import type { PartyCreditProfileFVO } from './partyCreditProfileFVO';
import type { ExternalIdentifierFVO } from './externalIdentifierFVO';
import type { CharacteristicFVO } from './characteristicFVO';
import type { RelatedPartyOrPartyRoleFVO } from './relatedPartyOrPartyRoleFVO';
import type { TaxExemptionCertificateFVO } from './taxExemptionCertificateFVO';

/**
 * Generic and Abstract Party structure used to define commonalities between sub concepts of Individual and Organization.
 */
export type PartyFVOAllOf = {
  /** List of means for contacting the party, e.g. mobile phone, email address */
  contactMedium?: ContactMediumFVO[];
  /** List of credit profiles and scores for the party, typically received from an external credit broker */
  creditRating?: PartyCreditProfileFVO[];
  /** List of identifiers of the Party in an external system, for example when party information is imported from a commerce system */
  externalReference?: ExternalIdentifierFVO[];
  /** List of additional characteristics that a Party can take on. */
  partyCharacteristic?: CharacteristicFVO[];
  /** List of parties and/or party roles related to this party */
  relatedParty?: RelatedPartyOrPartyRoleFVO[];
  /** List of tax exemptions granted to the party. For example, a war veteran might have partial exemption from state tax and a full exemption from federal tax */
  taxExemptionCertificate?: TaxExemptionCertificateFVO[];
};
