/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { PriceFVO } from './priceFVO';
import type { ProductOfferingPriceRefFVO } from './productOfferingPriceRefFVO';

/**
 * Is an amount, usually of money, that modifies the price charged for an order item.
 */
export type PriceAlterationFVOAllOf = {
  /** Duration during which the alteration applies on the order item price (for instance 2 months free of charge for the recurring charge) */
  applicationDuration?: number;
  /** A narrative that explains in detail the semantics of this order item price alteration */
  description?: string;
  /** Name of the order item price alteration */
  name?: string;
  price: PriceFVO;
  /** A category that describes the price such as recurring, one time and usage. */
  priceType: string;
  /** Priority level for applying this alteration among all the defined alterations on the order item price */
  priority?: number;
  productOfferingPrice?: ProductOfferingPriceRefFVO;
  /** Could be month, week... */
  recurringChargePeriod?: string;
  /** Could be minutes, GB... */
  unitOfMeasure?: string;
};
