/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { AgreementItemRefMVO } from './agreementItemRefMVO';
import type { BillingAccountRefMVO } from './billingAccountRefMVO';
import type { IntentRefOrValueMVO } from './intentRefOrValueMVO';
import type { RelatedPlaceRefOrValueMVO } from './relatedPlaceRefOrValueMVO';
import type { ProductRefOrValueMVO } from './productRefOrValueMVO';
import type { CharacteristicMVO } from './characteristicMVO';
import type { ProductOfferingRefMVO } from './productOfferingRefMVO';
import type { RelatedOrderItemMVO } from './relatedOrderItemMVO';
import type { ProductPriceMVO } from './productPriceMVO';
import type { ProductRelationshipMVO } from './productRelationshipMVO';
import type { ProductSpecificationRefMVO } from './productSpecificationRefMVO';
import type { ProductTermMVO } from './productTermMVO';
import type { ResourceRefMVO } from './resourceRefMVO';
import type { ServiceRefMVO } from './serviceRefMVO';
import type { RelatedPartyOrPartyRoleMVO } from './relatedPartyOrPartyRoleMVO';
import type { ProductStatusType } from './productStatusType';

/**
 * A product offering procured by a customer or other interested party playing a party role. A product is realized as one or more service(s) and / or resource(s).
 */
export type ProductMVOAllOf = {
  agreementItem?: AgreementItemRefMVO[];
  billingAccount?: BillingAccountRefMVO;
  /** Date and time when the product was created */
  creationDate?: string;
  /** Is the description of the product. It could be copied from the description of the Product Offering. */
  description?: string;
  intent?: IntentRefOrValueMVO;
  /** If true, the product is a ProductBundle which is an instantiation of a BundledProductOffering. If false, the product is a ProductComponent which is an instantiation of a SimpleProductOffering. */
  isBundle?: boolean;
  /** If true, the product is visible by the customer. */
  isCustomerVisible?: boolean;
  /** Name of the product. It could be the same as the name of the product offering */
  name?: string;
  /** Is the date when the product was ordered */
  orderDate?: string;
  place?: RelatedPlaceRefOrValueMVO[];
  product?: ProductRefOrValueMVO[];
  productCharacteristic?: CharacteristicMVO[];
  productOffering?: ProductOfferingRefMVO;
  productOrderItem?: RelatedOrderItemMVO[];
  productPrice?: ProductPriceMVO[];
  productRelationship?: ProductRelationshipMVO[];
  /** Is the serial number for the product. This is typically applicable to tangible products e.g. Broadband Router. */
  productSerialNumber?: string;
  productSpecification?: ProductSpecificationRefMVO;
  productTerm?: ProductTermMVO[];
  realizingResource?: ResourceRefMVO[];
  realizingService?: ServiceRefMVO[];
  relatedParty?: RelatedPartyOrPartyRoleMVO[];
  /** Is the date from which the product starts */
  startDate?: string;
  status?: ProductStatusType;
  /** Is the date when the product was terminated */
  terminationDate?: string;
};
