/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { TimePeriod } from './timePeriod';

/**
 * Reference of a tax definition. A tax is levied by an authorized tax jurisdiction. For example, there are many different types of tax (Federal Tax levied by the US Government, State Tax levied by the State of California, City Tax levied by the City of Los Angeles, etc.).
 */
export type TaxDefinitionAllOf = {
  /** Unique identifier of the tax. */
  id?: string;
  /** Level of the jurisdiction that levies the tax */
  jurisdictionLevel?: string;
  /** Name of the jurisdiction that levies the tax */
  jurisdictionName?: string;
  /** Tax name. */
  name?: string;
  /** Type of the tax. */
  taxType?: string;
  validFor?: TimePeriod;
};
