/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event. 
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase. 
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service. 
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import type { AttachmentRefOrValue } from './attachmentRefOrValue';
import type { TaxDefinition } from './taxDefinition';
import type { TimePeriod } from './timePeriod';

/**
 * A tax exemption certificate represents a tax exemption granted to a party (individual or organization) by a tax jurisdiction which may be a city, state, country,... An exemption has a certificate identifier (received from the jurisdiction that levied the tax) and a validity period. An exemption is per tax types and determines for each type of tax what portion of the tax is exempted (partial by percentage or complete) via the tax definition.
 */
export type TaxExemptionCertificateAllOf = {
  attachment?: AttachmentRefOrValue;
  /** Identifier of a document that shows proof of exemption from taxes for the taxing jurisdiction */
  certificateNumber?: string;
  /** Identifier of the tax exemption within list of the exemptions */
  id?: string;
  /** Name of the jurisdiction that issued the exemption */
  issuingJurisdiction?: string;
  /** Reason for the tax exemption */
  reason?: string;
  /** A list of taxes that are covered by the exemption, e.g. City Tax, State Tax. The definition would include the exemption (e.g. for a rate exemption 0% would be a full exemption, 5% could be a partial exemption if the actual rate was 10%). */
  taxDefinition?: TaxDefinition[];
  validFor?: TimePeriod;
};
