// Auto-generated from runtime/types/types.json
// 125 TMF entity types with 8+ fields

export interface TmfEntityType {
  name: string;
  fields: Record<string, string>;
}

export const TMF_ENTITIES: TmfEntityType[] = [
  {
    "name": "AccountRelationship",
    "fields": {
      "relationshipType": "string",
      "validFor": "TimePeriod",
      "account": "AccountRef",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "AckAlarm",
    "fields": {
      "state": "string",
      "ackSystemId": "string",
      "ackTime": "string",
      "ackUserId": "string",
      "ackedAlarm": "array<OneOfAlarmRefOrValue>",
      "alarmPattern": "array<OneOfAlarmRefOrValue>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "AgreementRelationship",
    "fields": {
      "id": "string",
      "name": "string",
      "relationshipType": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Alarm",
    "fields": {
      "externalAlarmId": "string",
      "state": "string",
      "alarmType": "AlarmType",
      "perceivedSeverity": "PerceivedSeverity",
      "probableCause": "string",
      "specificProblem": "string",
      "alarmedObjectType": "string",
      "alarmedObject": "AlarmedObjectRef",
      "reportingSystemId": "string",
      "sourceSystemId": "string",
      "alarmDetails": "string",
      "alarmRaisedTime": "string",
      "alarmChangedTime": "string",
      "alarmClearedTime": "string",
      "alarmReportingTime": "string",
      "ackState": "string",
      "ackSystemId": "string",
      "ackUserId": "string",
      "affectedService": "array<ServiceRef>",
      "alarmEscalation": "boolean",
      "clearSystemId": "string",
      "clearUserId": "string",
      "comment": "array<Comment>",
      "correlatedAlarm": "array<AlarmRef>",
      "crossedThresholdInformation": "CrossedThresholdInformation",
      "isRootCause": "boolean",
      "parentAlarm": "array<AlarmRef>",
      "plannedOutageIndicator": "string",
      "proposedRepairedActions": "string",
      "serviceAffecting": "boolean",
      "place": "array<RelatedPlace>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ApiProduct",
    "fields": {
      "name": "string",
      "description": "string",
      "productOffering": "OneOfProductOfferingRef",
      "productSpecification": "ProductSpecificationRef",
      "apiName": "string",
      "apiVersionDetails": "array<ApiVersionDetails>",
      "productOrderItem": "array<RelatedOrderItem>",
      "approvedProductOfferingTermOrCondition": "array<ProductOfferingTermOrCondition>",
      "status": "ProductStatusType",
      "creationDate": "string",
      "startDate": "string",
      "orderDate": "string",
      "terminationDate": "string",
      "channelPartner": "PartyRoleRef",
      "agreementItem": "array<AgreementItemRef>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ApiProductOrder",
    "fields": {
      "description": "string",
      "externalId": "array<ExternalIdentifier>",
      "productOrderItem": "array<DCSProductOrderItem>",
      "agreement": "array<AgreementRef>",
      "channelPartner": "PartyRoleRef",
      "state": "ProductOrderStateType",
      "creationDate": "string",
      "expectedCompletionDate": "string",
      "completionDate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Application",
    "fields": {
      "commercialName": "string",
      "logoUrl": "string",
      "privacyPolicyURL": "string",
      "category": "string",
      "approvalStatus": "ApprovalStatusType",
      "approvalStatusReason": "string",
      "applicationOwner": "PartyRoleRef",
      "channelPartner": "PartyRoleRef",
      "digitalIdentity": "ApiDigitalIdentity",
      "apiConsumerRole": "array<LogicalResourceRole>",
      "description": "string",
      "name": "string",
      "operationalState": "ResourceOperationalStateType",
      "resourceVersion": "string",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ApplicationOwner",
    "fields": {
      "name": "string",
      "description": "string",
      "engagedParty": "ApplicationOwnerOrganization",
      "channelPartner": "PartyRoleRef",
      "approvalStatus": "ApprovalStatusType",
      "approvalStatusReason": "string",
      "status": "ApplicationOwnerStatusType",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "AppliedBillingTaxRate",
    "fields": {
      "taxAmount": "Money",
      "taxCategory": "string",
      "taxRate": "number",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "AppliedCustomerBillingRate",
    "fields": {
      "appliedTax": "array<AppliedBillingTaxRate>",
      "bill": "CustomerBillRef",
      "date": "string",
      "description": "string",
      "isBilled": "boolean",
      "name": "string",
      "periodCoverage": "TimePeriod",
      "taxExcludedAmount": "Money",
      "taxIncludedAmount": "Money",
      "appliedBillingRateType": "string",
      "billingAccount": "BillingAccountRef",
      "product": "ProductRef",
      "characteristic": "array<OneOfCharacteristic>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Attachment",
    "fields": {
      "name": "string",
      "description": "string",
      "url": "string",
      "content": "string",
      "size": "Quantity",
      "validFor": "TimePeriod",
      "attachmentType": "string",
      "mimeType": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "BatchJob",
    "fields": {
      "id": "string",
      "href": "string",
      "name": "string",
      "description": "string",
      "state": "string",
      "category": "string",
      "priority": "integer",
      "scheduledStartDate": "string",
      "startDate": "string",
      "completionDate": "string",
      "expectedCompletionDate": "string",
      "executionWindowStart": "string",
      "executionWindowEnd": "string",
      "requestedQuantity": "integer",
      "actualQuantity": "integer",
      "x_summary": "string",
      "x_currentItemId": "string",
      "x_currentItemState": "string",
      "x_configuration": "string",
      "x_lastError": "string",
      "x_recurrencePattern": "string",
      "x_isRecurrent": "boolean",
      "x_parentScheduleId": "string",
      "x_executionNumber": "integer",
      "creationDate": "string",
      "lastUpdate": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "BatchSchedule",
    "fields": {
      "id": "string",
      "href": "string",
      "name": "string",
      "description": "string",
      "isActive": "boolean",
      "category": "string",
      "recurrencePattern": "string",
      "windowStartTime": "string",
      "windowEndTime": "string",
      "timezone": "string",
      "maxBatchSize": "integer",
      "selectionCriteria": "string",
      "validFrom": "string",
      "validTo": "string",
      "createdBy": "string",
      "totalExecutions": "integer",
      "successfulExecutions": "integer",
      "failedExecutions": "integer",
      "lastExecutionId": "string",
      "lastExecutionDate": "string",
      "nextExecutionDate": "string",
      "creationDate": "string",
      "lastUpdate": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "BillCycle",
    "fields": {
      "billingDate": "string",
      "billingPeriod": "string",
      "chargeDate": "string",
      "creditDate": "string",
      "description": "string",
      "mailingDate": "string",
      "name": "string",
      "paymentDueDate": "string",
      "BillCycleSpecification": "BillCycleSpecificationRef",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "BillingAccount",
    "fields": {
      "ratingType": "string",
      "paymentStatus": "string",
      "billStructure": "BillStructure",
      "paymentPlan": "array<PaymentPlan>",
      "financialAccount": "FinancialAccountRef",
      "defaultPaymentMethod": "PaymentMethodRef",
      "creditLimit": "Money",
      "description": "string",
      "lastUpdate": "string",
      "name": "string",
      "state": "string",
      "accountType": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "taxExemption": "array<TaxExemptionCertificate>",
      "contact": "array<Contact>",
      "accountBalance": "array<AccountBalance>",
      "accountRelationship": "array<AccountRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "BillingCycleSpecification",
    "fields": {
      "name": "string",
      "billingDateShift": "integer",
      "billingPeriod": "string",
      "chargeDateOffset": "integer",
      "creditDateOffset": "integer",
      "description": "string",
      "frequency": "string",
      "mailingDateOffset": "integer",
      "paymentDueDateOffset": "integer",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "BundledProductOffering",
    "fields": {
      "bundledProductOfferingOption": "BundledProductOfferingOption",
      "version": "string",
      "id": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "BundledProductOfferingPriceRelationship",
    "fields": {
      "version": "string",
      "id": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "BundledProductSpecification",
    "fields": {
      "href": "string",
      "id": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "version": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "BusinessPartner",
    "fields": {
      "name": "string",
      "description": "string",
      "role": "string",
      "engagedParty": "PartyRef",
      "partyRoleSpecification": "OneOfPartyRoleSpecificationRef",
      "characteristic": "array<OneOfCharacteristic>",
      "account": "array<AccountRef>",
      "agreement": "array<AgreementRef>",
      "contactMedium": "array<OneOfContactMedium>",
      "paymentMethod": "array<PaymentMethodRef>",
      "creditProfile": "array<CreditProfile>",
      "relatedParty": "array<jsonb<RelatedPartyOrPartyRole>>",
      "status": "string",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CancelProductOrder",
    "fields": {
      "productOrder": "ProductOrderRef",
      "creationDate": "string",
      "requestedCancellationDate": "string",
      "cancellationReason": "string",
      "state": "TaskStateType",
      "effectiveCancellationDate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Category",
    "fields": {
      "description": "string",
      "isRoot": "boolean",
      "parent": "CategoryRef",
      "productOffering": "array<OneOfProductOfferingRef>",
      "subCategory": "array<CategoryRef>",
      "validFor": "TimePeriod",
      "version": "string",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CdrTransaction",
    "fields": {
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "state": "CdrTransactionStateType",
      "requestedInitialState": "CdrTransactionInitialStateType",
      "cancellationDate": "string",
      "cancellationReason": "string",
      "channel": "array<RelatedChannel>",
      "description": "string",
      "note": "array<Note>",
      "transactionItem": "array<CdrTransactionItem>",
      "creationDate": "string",
      "completionDate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CheckProductConfiguration",
    "fields": {
      "channel": "ChannelRef",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "contextEntity": "EntityRef",
      "contextCharacteristic": "array<OneOfCharacteristic>",
      "instantSync": "boolean",
      "provideAlternatives": "boolean",
      "state": "TaskStateType",
      "checkProductConfigurationItem": "array<CheckProductConfigurationItem>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CheckProductOfferingQualification",
    "fields": {
      "href": "string",
      "id": "string",
      "channel": "ChannelRef",
      "description": "string",
      "effectiveQualificationDate": "string",
      "expectedQualificationCompletionDate": "string",
      "expirationDate": "string",
      "instantSyncQualification": "boolean",
      "note": "array<Note>",
      "checkProductOfferingQualificationItem": "array<CheckProductOfferingQualificationItem>",
      "provideAlternative": "boolean",
      "provideOnlyAvailable": "boolean",
      "provideResultReason": "boolean",
      "qualificationResult": "string",
      "relatedParty": "array<RelatedPartyOrPartyRole>",
      "requestedQualificationCompletionDate": "string",
      "state": "TaskStateType",
      "creationDate": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ClearAlarm",
    "fields": {
      "state": "string",
      "clearSystemId": "string",
      "clearUserId": "string",
      "alarmClearedTime": "string",
      "alarmPattern": "array<OneOfAlarmRefOrValue>",
      "clearedAlarm": "array<OneOfAlarmRefOrValue>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CommentAlarm",
    "fields": {
      "id": "string",
      "href": "string",
      "state": "string",
      "comment": "Comment",
      "alarmPattern": "array<OneOfAlarmRefOrValue>",
      "commentedAlarm": "array<OneOfAlarmRefOrValue>",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ConnectionSpecification",
    "fields": {
      "name": "string",
      "associationType": "string",
      "endpointSpecification": "array<EndpointSpecificationRef>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Consumer",
    "fields": {
      "name": "string",
      "description": "string",
      "role": "string",
      "engagedParty": "PartyRef",
      "partyRoleSpecification": "OneOfPartyRoleSpecificationRef",
      "characteristic": "array<OneOfCharacteristic>",
      "account": "array<AccountRef>",
      "agreement": "array<AgreementRef>",
      "contactMedium": "array<OneOfContactMedium>",
      "paymentMethod": "array<PaymentMethodRef>",
      "creditProfile": "array<CreditProfile>",
      "relatedParty": "array<jsonb<RelatedPartyOrPartyRole>>",
      "status": "string",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CreditProfile",
    "fields": {
      "creditProfileDate": "string",
      "creditRiskRating": "integer",
      "creditScore": "integer",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Customer",
    "fields": {
      "name": "string",
      "description": "string",
      "role": "string",
      "engagedParty": "PartyRef",
      "partyRoleSpecification": "OneOfPartyRoleSpecificationRef",
      "characteristic": "array<OneOfCharacteristic>",
      "account": "array<AccountRef>",
      "agreement": "array<AgreementRef>",
      "contactMedium": "array<OneOfContactMedium>",
      "paymentMethod": "array<PaymentMethodRef>",
      "creditProfile": "array<CreditProfile>",
      "relatedParty": "array<RelatedPartyOrPartyRole>",
      "status": "string",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CustomerBill",
    "fields": {
      "amountDue": "Money",
      "appliedPayment": "array<AppliedPayment>",
      "billDate": "string",
      "billDocument": "array<OneOfAttachmentRefOrValue>",
      "billNo": "string",
      "billingAccount": "BillingAccountRef",
      "billingPeriod": "TimePeriod",
      "billCycle": "BillCycleRef",
      "category": "string",
      "financialAccount": "FinancialAccountRef",
      "lastUpdate": "string",
      "nextBillDate": "string",
      "paymentDueDate": "string",
      "paymentMethod": "PaymentMethodRef",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "remainingAmount": "Money",
      "runType": "CustomerBillRunType",
      "taxExcludedAmount": "Money",
      "taxIncludedAmount": "Money",
      "taxItem": "array<TaxItem>",
      "state": "CustomerBillStateType",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "CustomerBillOnDemand",
    "fields": {
      "name": "string",
      "state": "CustomerBillOnDemandStateType",
      "billingAccount": "BillingAccountRef",
      "customerBill": "CustomerBillRef",
      "description": "string",
      "lastUpdate": "string",
      "relatedParty": "RelatedPartyRefOrPartyRoleRef",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Document",
    "fields": {
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "category": "array<CategoryRef>",
      "characteristic": "array<OneOfCharacteristic>",
      "creationDate": "string",
      "description": "string",
      "documentRelationship": "array<DocumentRef>",
      "documentSpecification": "DocumentSpecification",
      "lastUpdate": "string",
      "lifecycleState": "string",
      "relatedEntity": "RelatedEntity",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "documentType": "string",
      "version": "string",
      "name": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "EntityRelationship",
    "fields": {
      "href": "string",
      "name": "string",
      "role": "string",
      "validFor": "TimePeriod",
      "associationSpec": "EntityRef",
      "@baseType": "string",
      "@schemaLocation": "string",
      "relationshipType": "string",
      "id": "string",
      "@referredType": "string",
      "@type": "string"
    }
  },
  {
    "name": "FailedMigrationProduct",
    "fields": {
      "name": "string",
      "description": "string",
      "solutionType": "string",
      "status": "string",
      "migrationStatus": "string",
      "createdByName": "string",
      "createdDate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "FinancialAccount",
    "fields": {
      "creditLimit": "Money",
      "description": "string",
      "lastUpdate": "string",
      "name": "string",
      "state": "string",
      "accountType": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "taxExemption": "array<TaxExemptionCertificate>",
      "contact": "array<Contact>",
      "accountBalance": "array<AccountBalance>",
      "accountRelationship": "array<AccountRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "GeographicAddress",
    "fields": {
      "city": "string",
      "country": "string",
      "locality": "string",
      "postcode": "string",
      "stateOrProvince": "string",
      "streetName": "string",
      "streetNr": "string",
      "streetNrLast": "string",
      "streetNrLastSuffix": "string",
      "streetNrSuffix": "string",
      "streetSuffix": "string",
      "streetType": "string",
      "countryCode": "array<StandardIdentifier>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "geographicLocation": "OneOfGeographicLocationRefOrValue",
      "geographicSubAddress": "array<GeographicSubAddress>",
      "geographicAddressType": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "GeographicSite",
    "fields": {
      "code": "string",
      "creationDate": "string",
      "description": "string",
      "status": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "calendar": "array<CalendarPeriod>",
      "place": "array<jsonb<PlaceRefOrValue>>",
      "siteRelationship": "array<GeographicSiteRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "GeographicSiteRelationship",
    "fields": {
      "href": "string",
      "role": "string",
      "validFor": "TimePeriod",
      "id": "string",
      "relationshipType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "GeographicSubAddress",
    "fields": {
      "buildingName": "string",
      "href": "string",
      "id": "string",
      "levelNumber": "string",
      "levelType": "string",
      "name": "string",
      "privateStreetName": "string",
      "privateStreetNumber": "string",
      "subUnit": "array<GeographicSubAddressUnit>",
      "subAddressType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "GroupAlarm",
    "fields": {
      "id": "string",
      "href": "string",
      "state": "string",
      "sourceSystemId": "string",
      "alarmChangedTime": "string",
      "parentAlarm": "OneOfAlarmRefOrValue",
      "correlatedAlarm": "array<OneOfAlarmRefOrValue>",
      "groupedAlarm": "array<OneOfAlarmRefOrValue>",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Individual",
    "fields": {
      "gender": "string",
      "placeOfBirth": "string",
      "countryOfBirth": "string",
      "nationality": "string",
      "maritalStatus": "string",
      "birthDate": "string",
      "deathDate": "string",
      "title": "string",
      "aristocraticTitle": "string",
      "generation": "string",
      "preferredGivenName": "string",
      "familyNamePrefix": "string",
      "legalName": "string",
      "middleName": "string",
      "name": "string",
      "formattedName": "string",
      "location": "string",
      "status": "IndividualStateType",
      "otherName": "array<OtherNameIndividual>",
      "individualIdentification": "array<IndividualIdentification>",
      "disability": "array<Disability>",
      "languageAbility": "array<LanguageAbility>",
      "skill": "array<Skill>",
      "familyName": "string",
      "givenName": "string",
      "externalReference": "array<ExternalIdentifier>",
      "partyCharacteristic": "array<OneOfCharacteristic>",
      "taxExemptionCertificate": "array<TaxExemptionCertificate>",
      "creditRating": "array<PartyCreditProfile>",
      "relatedParty": "array<jsonb<RelatedPartyOrPartyRole>>",
      "contactMedium": "array<OneOfContactMedium>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Intent",
    "fields": {
      "description": "string",
      "validFor": "TimePeriod",
      "isBundle": "boolean",
      "priority": "string",
      "statusChangeDate": "string",
      "context": "string",
      "version": "string",
      "intentSpecification": "EntityRef",
      "intentRelationship": "array<EntityRelationship>",
      "characteristic": "array<OneOfCharacteristic>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "name": "string",
      "expression": "Expression",
      "creationDate": "string",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "IntentReport",
    "fields": {
      "description": "string",
      "validFor": "TimePeriod",
      "intent": "OneOfIntentRefOrValue",
      "name": "string",
      "expression": "OneOfIntentExpression",
      "creationDate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "IntentSpecification",
    "fields": {
      "expressionSpecification": "ExpressionSpecification",
      "intentSpecRelationship": "array<IntentSpecificationRelationship>",
      "isBundle": "boolean",
      "version": "string",
      "name": "string",
      "description": "string",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "validFor": "TimePeriod",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "targetEntitySchema": "TargetEntitySchema",
      "specCharacteristic": "array<CharacteristicSpecification>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "constraint": "array<ConstraintRef>",
      "entitySpecRelationship": "array<EntitySpecificationRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "IntentSpecificationRelationship",
    "fields": {
      "role": "string",
      "relationshipType": "string",
      "validFor": "TimePeriod",
      "id": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "InteractionRelationship",
    "fields": {
      "id": "string",
      "relationshipType": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "LogicalResourceSpecification",
    "fields": {
      "description": "string",
      "version": "string",
      "validFor": "TimePeriod",
      "isBundle": "boolean",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "category": "string",
      "targetResourceSchema": "TargetResourceSchema",
      "featureSpecification": "array<FeatureSpecification>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "resourceSpecCharacteristic": "array<CharacteristicSpecification>",
      "resourceSpecRelationship": "array<ResourceSpecificationRelationship>",
      "intentSpecification": "IntentSpecificationRef",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "MigrationStatus",
    "fields": {
      "id": "string",
      "href": "string",
      "solutionId": "string",
      "status": "string",
      "subscriptionCount": "string",
      "message": "string",
      "success": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "Monitor",
    "fields": {
      "request": "Request",
      "response": "Response",
      "sourceHref": "string",
      "state": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "OeServiceAttachment",
    "fields": {
      "id": "string",
      "href": "string",
      "serviceId": "string",
      "attachmentContent": "string",
      "attachmentId": "string",
      "backupAttachmentId": "string",
      "success": "string",
      "message": "string",
      "errorCode": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "OeServiceInfo",
    "fields": {
      "id": "string",
      "href": "string",
      "serviceId": "string",
      "serviceName": "string",
      "productDefinitionName": "string",
      "replacementServiceExists": "string",
      "attachmentId": "string",
      "attachmentContent": "string",
      "success": "string",
      "message": "string",
      "errorCode": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "OeServiceRemediation",
    "fields": {
      "id": "string",
      "href": "string",
      "serviceId": "string",
      "productDefinitionName": "string",
      "remediationId": "string",
      "status": "string",
      "success": "string",
      "message": "string",
      "errorCode": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "OrderRelationship",
    "fields": {
      "@referredType": "string",
      "id": "string",
      "relationshipType": "string",
      "href": "string",
      "name": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Organization",
    "fields": {
      "isLegalEntity": "boolean",
      "isHeadOffice": "boolean",
      "organizationType": "string",
      "existsDuring": "TimePeriod",
      "name": "string",
      "nameType": "string",
      "status": "OrganizationStateType",
      "otherName": "array<OtherNameOrganization>",
      "organizationIdentification": "array<OrganizationIdentification>",
      "organizationChildRelationship": "array<OrganizationChildRelationship>",
      "organizationParentRelationship": "OrganizationParentRelationship",
      "tradingName": "string",
      "externalReference": "array<ExternalIdentifier>",
      "partyCharacteristic": "array<OneOfCharacteristic>",
      "taxExemptionCertificate": "array<TaxExemptionCertificate>",
      "creditRating": "array<PartyCreditProfile>",
      "relatedParty": "array<jsonb<RelatedPartyOrPartyRole>>",
      "contactMedium": "array<OneOfContactMedium>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyAccount",
    "fields": {
      "paymentStatus": "string",
      "billStructure": "BillStructure",
      "paymentPlan": "array<PaymentPlan>",
      "financialAccount": "FinancialAccountRef",
      "defaultPaymentMethod": "PaymentMethodRef",
      "creditLimit": "Money",
      "description": "string",
      "lastUpdate": "string",
      "name": "string",
      "state": "string",
      "accountType": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "taxExemption": "array<TaxExemptionCertificate>",
      "contact": "array<Contact>",
      "accountBalance": "array<AccountBalance>",
      "accountRelationship": "array<AccountRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyCreditProfile",
    "fields": {
      "creditAgencyName": "string",
      "creditAgencyType": "string",
      "ratingReference": "string",
      "ratingScore": "integer",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyInteraction",
    "fields": {
      "relatedChannel": "array<RelatedChannel>",
      "direction": "string",
      "reason": "string",
      "interactionDate": "TimePeriod",
      "description": "string",
      "status": "string",
      "statusChangeDate": "string",
      "creationDate": "string",
      "lastUpdate": "string",
      "relatedParty": "array<RelatedPartyOrPartyRole>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "note": "array<Note>",
      "interactionItem": "array<InteractionItem>",
      "interactionRelationship": "array<InteractionRelationship>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyPrivacyAgreement",
    "fields": {
      "partyPrivacyProfile": "array<PartyPrivacyProfileRef>",
      "partyPrivacyProfileCharacteristic": "array<PartyPrivacyProfileCharacteristic>",
      "name": "string",
      "agreementType": "string",
      "agreementItem": "array<OneOfAgreementItem>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "engagedParty": "array<OneOfPartyRefOrPartyRoleRef>",
      "agreementPeriod": "TimePeriod",
      "completionDate": "TimePeriod",
      "description": "string",
      "relatedDocument": "array<RelatedDocumentRefOrValue>",
      "initialDate": "string",
      "statementOfIntent": "string",
      "status": "string",
      "version": "string",
      "agreementSpecification": "AgreementSpecificationRef",
      "agreementAuthorization": "array<AgreementAuthorization>",
      "characteristic": "array<OneOfCharacteristic>",
      "agreementRelationship": "array<AgreementRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyPrivacyProfile",
    "fields": {
      "applicableForParty": "RelatedPartyRefOrPartyRoleRef",
      "agreement": "PartyPrivacyAgreementRef",
      "creationDate": "string",
      "lastUpdate": "string",
      "description": "string",
      "name": "string",
      "status": "string",
      "validFor": "TimePeriod",
      "partyPrivacyProfileSpecification": "PartyPrivacyProfileSpecificationRef",
      "partyPrivacyProfileCharacteristic": "array<PartyPrivacyProfileCharacteristic>",
      "agreedByParty": "RelatedPartyRefOrPartyRoleRef",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyPrivacyProfileSpecification",
    "fields": {
      "description": "string",
      "applicableRole": "array<PartyPrivacyRoleSpecification>",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "productOffering": "array<ProductOfferingRef>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "validFor": "TimePeriod",
      "version": "string",
      "specCharacteristic": "array<PartyPrivacyProfileSpecificationCharacteristic>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyPrivacyRoleSpecification",
    "fields": {
      "agreementSpecification": "array<AgreementSpecificationRef>",
      "id": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingAlgorithm",
    "fields": {
      "name": "string",
      "description": "string",
      "policy": "array<PolicyRef>",
      "conditionVariable": "array<PartyRevSharingPolicyConditionVariable>",
      "actionVariable": "array<PartyRevSharingPolicyActionVariable>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingModel",
    "fields": {
      "name": "string",
      "description": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "partyRevSharingModelItem": "array<PartyRevSharingModelItem>",
      "productSpecification": "array<ProductSpecificationRef>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingModelInvolPrice",
    "fields": {
      "name": "string",
      "description": "string",
      "productOfferingPrice": "ProductOfferingPriceRef",
      "partyRevSharingAlgorithm": "array<PartyRevSharingAlgorithmRef>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingModelItem",
    "fields": {
      "name": "string",
      "description": "string",
      "relatedParty": "RelatedPartyRefOrPartyRoleRef",
      "partyAccount": "PartyAccountRef",
      "sharingModelItemInvolvement": "array<PartyRevSharingModelItemInvolvement>",
      "agreement": "array<AgreementRef>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingModelItemInvolvement",
    "fields": {
      "name": "string",
      "description": "string",
      "productOffering": "array<OneOfProductOfferingRef>",
      "offeringPrice": "array<PartyRevSharingModelInvolPrice>",
      "agreementItem": "array<AgreementItemRef>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingPolicyActionVariable",
    "fields": {
      "value": "string",
      "policyAction": "PolicyActionRef",
      "policyActionVariable": "PolicyVariableRef",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingPolicyConditionVariable",
    "fields": {
      "value": "string",
      "policyCondition": "PolicyConditionRef",
      "policyConditionVariable": "PolicyVariableRef",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingReport",
    "fields": {
      "partyRevSharingModel": "PartyRevSharingModelRef",
      "cdrTransaction": "CdrTransactionRef",
      "partyRevSharingReportItem": "array<PartyRevSharingReportItem>",
      "money": "Money",
      "createDate": "string",
      "lastUpdate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingReportItem",
    "fields": {
      "partyRevSharingModelItem": "PartyRevSharingModelItemRef",
      "relatedParty": "RelatedPartyRefOrPartyRoleRef",
      "partyAccount": "PartyAccountRef",
      "cdrTransactionItem": "CdrTransactionItemRef",
      "billPeriod": "TimePeriod",
      "sharingReportItemIDetail": "array<PartyRevSharingReportItemDetail>",
      "money": "Money",
      "bill": "CustomerBillRef",
      "payment": "PaymentRef",
      "status": "string",
      "createDate": "string",
      "lastUpdate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRevSharingReportItemDetail",
    "fields": {
      "partyRevSharingModelInvolPrice": "PartyRevSharingModelInvolPriceRef",
      "product": "array<ProductRef>",
      "productOffering": "OneOfProductOfferingRef",
      "productOfferingPrice": "ProductOfferingPriceRef",
      "partyRevSharingAlgorithm": "array<PartyRevSharingAlgorithmRef>",
      "money": "Money",
      "status": "string",
      "createDate": "string",
      "lastUpdate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRole",
    "fields": {
      "name": "string",
      "description": "string",
      "role": "string",
      "engagedParty": "PartyRef",
      "partyRoleSpecification": "OneOfPartyRoleSpecificationRef",
      "characteristic": "array<OneOfCharacteristic>",
      "account": "array<AccountRef>",
      "agreement": "array<AgreementRef>",
      "contactMedium": "array<OneOfContactMedium>",
      "paymentMethod": "array<PaymentMethodRef>",
      "creditProfile": "array<CreditProfile>",
      "relatedParty": "array<jsonb<RelatedPartyOrPartyRole>>",
      "status": "string",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PartyRoleSpecification",
    "fields": {
      "agreementSpecification": "array<AgreementSpecificationRef>",
      "permissionSpecificationSet": "array<PermissionSpecificationSetRef>",
      "status": "string",
      "name": "string",
      "description": "string",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "isBundle": "boolean",
      "validFor": "TimePeriod",
      "version": "string",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "targetEntitySchema": "TargetEntitySchema",
      "specCharacteristic": "array<CharacteristicSpecification>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "constraint": "array<ConstraintRef>",
      "entitySpecRelationship": "array<EntitySpecificationRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PhysicalResourceSpecification",
    "fields": {
      "model": "string",
      "part": "string",
      "sku": "string",
      "vendor": "string",
      "description": "string",
      "version": "string",
      "validFor": "TimePeriod",
      "isBundle": "boolean",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "category": "string",
      "targetResourceSchema": "TargetResourceSchema",
      "featureSpecification": "array<FeatureSpecification>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "resourceSpecCharacteristic": "array<CharacteristicSpecification>",
      "resourceSpecRelationship": "array<ResourceSpecificationRelationship>",
      "intentSpecification": "IntentSpecificationRef",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "PricingLogicAlgorithm",
    "fields": {
      "description": "string",
      "name": "string",
      "plaSpecId": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProbeIntent",
    "fields": {
      "description": "string",
      "validFor": "TimePeriod",
      "isBundle": "boolean",
      "priority": "string",
      "statusChangeDate": "string",
      "context": "string",
      "version": "string",
      "intentSpecification": "EntityRef",
      "intentRelationship": "array<EntityRelationship>",
      "characteristic": "array<OneOfCharacteristic>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "name": "string",
      "expression": "OneOfIntentExpression",
      "creationDate": "string",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProblemAcknowledgement",
    "fields": {
      "ackProblem": "array<ServiceProblemRef>",
      "trackingRecord": "TrackingRecord",
      "problem": "array<ServiceProblemRef>",
      "state": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProblemGroup",
    "fields": {
      "childProblem": "array<ServiceProblemRef>",
      "parentProblem": "ServiceProblemRef",
      "state": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProblemUnacknowledgement",
    "fields": {
      "unackProblem": "array<ServiceProblemRef>",
      "trackingRecord": "TrackingRecord",
      "problem": "array<ServiceProblemRef>",
      "state": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProblemUngroup",
    "fields": {
      "childProblem": "array<ServiceProblemRef>",
      "parentProblem": "ServiceProblemRef",
      "state": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Producer",
    "fields": {
      "name": "string",
      "description": "string",
      "role": "string",
      "engagedParty": "PartyRef",
      "partyRoleSpecification": "OneOfPartyRoleSpecificationRef",
      "characteristic": "array<OneOfCharacteristic>",
      "account": "array<AccountRef>",
      "agreement": "array<AgreementRef>",
      "contactMedium": "array<OneOfContactMedium>",
      "paymentMethod": "array<PaymentMethodRef>",
      "creditProfile": "array<CreditProfile>",
      "relatedParty": "array<jsonb<RelatedPartyOrPartyRole>>",
      "status": "string",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Product",
    "fields": {
      "agreementItem": "array<AgreementItemRef>",
      "billingAccount": "BillingAccountRef",
      "creationDate": "string",
      "description": "string",
      "isBundle": "boolean",
      "isCustomerVisible": "boolean",
      "name": "string",
      "orderDate": "string",
      "productCharacteristic": "array<OneOfCharacteristic>",
      "productOffering": "OneOfProductOfferingRef",
      "productOrderItem": "array<RelatedOrderItem>",
      "product": "array<OneOfProductRefOrValue>",
      "productPrice": "array<ProductPrice>",
      "productRelationship": "array<ProductRelationship>",
      "productSerialNumber": "string",
      "productSpecification": "ProductSpecificationRef",
      "productTerm": "array<ProductTerm>",
      "realizingResource": "array<ResourceRef>",
      "realizingService": "array<ServiceRef>",
      "relatedParty": "array<RelatedPartyOrPartyRole>",
      "place": "array<RelatedPlaceRefOrValue>",
      "startDate": "string",
      "status": "ProductStatusType",
      "terminationDate": "string",
      "intent": "OneOfIntentRefOrValue",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string",
      "x_parentBundleId": "string",
      "x_parentBundleName": "string"
    }
  },
  {
    "name": "ProductCatalog",
    "fields": {
      "category": "array<CategoryRef>",
      "description": "string",
      "catalogType": "string",
      "validFor": "TimePeriod",
      "version": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductOffering",
    "fields": {
      "description": "string",
      "isBundle": "boolean",
      "isSellable": "boolean",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "version": "string",
      "place": "array<PlaceRef>",
      "serviceLevelAgreement": "SLARef",
      "channel": "array<ChannelRef>",
      "serviceCandidate": "ServiceCandidateRef",
      "category": "array<CategoryRef>",
      "resourceCandidate": "ResourceCandidateRef",
      "productOfferingTerm": "array<ProductOfferingTerm>",
      "productOfferingPrice": "array<OneOfProductOfferingPriceRefOrValue>",
      "agreement": "array<AgreementRef>",
      "bundledProductOffering": "array<BundledProductOffering>",
      "bundledGroupProductOffering": "array<BundledGroupProductOffering>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "marketSegment": "array<MarketSegmentRef>",
      "productOfferingRelationship": "array<ProductOfferingRelationship>",
      "productOfferingCharacteristic": "array<CharacteristicSpecification>",
      "prodSpecCharValueUse": "array<ProductSpecificationCharacteristicValueUse>",
      "policy": "array<PolicyRef>",
      "allowedAction": "array<AllowedProductAction>",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "productSpecification": "ProductSpecificationRef",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductOfferingPrice",
    "fields": {
      "description": "string",
      "version": "string",
      "validFor": "TimePeriod",
      "unitOfMeasure": "Quantity",
      "recurringChargePeriodType": "string",
      "recurringChargePeriodLength": "integer",
      "isBundle": "boolean",
      "price": "Money",
      "percentage": "number",
      "bundledPopRelationship": "array<BundledProductOfferingPriceRelationship>",
      "popRelationship": "array<ProductOfferingPriceRelationship>",
      "prodSpecCharValueUse": "array<ProductSpecificationCharacteristicValueUse>",
      "productOfferingTerm": "array<ProductOfferingTerm>",
      "place": "array<PlaceRef>",
      "policy": "array<PolicyRef>",
      "pricingLogicAlgorithm": "array<PricingLogicAlgorithm>",
      "tax": "array<TaxItem>",
      "name": "string",
      "priceType": "string",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductOfferingPriceRelationship",
    "fields": {
      "role": "string",
      "relationshipType": "string",
      "version": "string",
      "id": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductOfferingRelationship",
    "fields": {
      "role": "string",
      "name": "string",
      "validFor": "TimePeriod",
      "relationshipType": "string",
      "version": "string",
      "id": "string",
      "href": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductOrder",
    "fields": {
      "agreement": "array<AgreementRef>",
      "billingAccount": "BillingAccountRef",
      "state": "ProductOrderStateType",
      "requestedInitialState": "InitialProductOrderStateType",
      "cancellationDate": "string",
      "cancellationReason": "string",
      "category": "string",
      "channel": "array<RelatedChannel>",
      "description": "string",
      "expectedCompletionDate": "string",
      "externalId": "array<ExternalIdentifier>",
      "note": "array<Note>",
      "notificationContact": "string",
      "orderTotalPrice": "array<OrderPrice>",
      "payment": "array<PaymentRef>",
      "orderRelationship": "array<OrderRelationship>",
      "priority": "string",
      "productOfferingQualification": "array<ProductOfferingQualificationRef>",
      "quote": "array<QuoteRef>",
      "productOrderErrorMessage": "array<ProductOrderErrorMessage>",
      "productOrderJeopardyAlert": "array<ProductOrderJeopardyAlert>",
      "productOrderMilestone": "array<ProductOrderMilestone>",
      "productOrderItem": "array<ProductOrderItem>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "requestedCompletionDate": "string",
      "requestedStartDate": "string",
      "creationDate": "string",
      "completionDate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductRelationship",
    "fields": {
      "id": "string",
      "relationshipType": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductSpecification",
    "fields": {
      "brand": "string",
      "description": "string",
      "isBundle": "boolean",
      "productNumber": "string",
      "category": "array<CategoryRef>",
      "validFor": "TimePeriod",
      "version": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "productSpecCharacteristic": "array<CharacteristicSpecification>",
      "serviceSpecification": "array<ServiceSpecificationRef>",
      "bundledProductSpecification": "array<BundledProductSpecification>",
      "productSpecificationRelationship": "array<ProductSpecificationRelationship>",
      "resourceSpecification": "array<ResourceSpecificationRef>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "policy": "array<PolicyRef>",
      "targetProductSchema": "TargetProductSchema",
      "intentSpecification": "IntentSpecificationRef",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ProductSpecificationRelationship",
    "fields": {
      "characteristic": "array<CharacteristicSpecification>",
      "validFor": "TimePeriod",
      "relationshipType": "string",
      "version": "string",
      "id": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "QueryProductConfiguration",
    "fields": {
      "channel": "ChannelRef",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "contextEntity": "EntityRef",
      "contextCharacteristic": "array<OneOfCharacteristic>",
      "instantSync": "boolean",
      "state": "TaskStateType",
      "requestProductConfigurationItem": "array<QueryProductConfigurationItem>",
      "computedProductConfigurationItem": "array<QueryProductConfigurationItem>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "QueryProductOfferingQualification",
    "fields": {
      "href": "string",
      "id": "string",
      "channel": "ChannelRef",
      "description": "string",
      "effectiveQualificationDate": "string",
      "expectedQualificationCompletionDate": "string",
      "expirationDate": "string",
      "instantSyncQualification": "boolean",
      "note": "array<Note>",
      "qualifiedProductOfferingItem": "array<QueryProductOfferingQualificationItem>",
      "searchCriteria": "QueryProductOfferingQualificationItem",
      "relatedParty": "array<RelatedPartyOrPartyRole>",
      "requestedQualificationCompletionDate": "string",
      "state": "TaskStateType",
      "creationDate": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "RemediatedProduct",
    "fields": {
      "id": "string",
      "href": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string",
      "name": "string",
      "remediationStatus": "string",
      "remediationJobId": "string",
      "lastRemediatedAt": "string",
      "remediationMessage": "string",
      "remediationModule": "string",
      "firstRemediatedAt": "string",
      "solutionStatus": "string",
      "solutionType": "string",
      "creationDate": "string",
      "migrationStatus": "string",
      "createdByName": "string",
      "isBundle": "boolean"
    }
  },
  {
    "name": "RemediationTask",
    "fields": {
      "id": "string",
      "href": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string",
      "solutionId": "string",
      "solutionName": "string",
      "module": "string",
      "status": "string",
      "jobId": "string",
      "createdAt": "string",
      "updatedAt": "string",
      "resultMessage": "string"
    }
  },
  {
    "name": "ResourceCandidate",
    "fields": {
      "description": "string",
      "version": "string",
      "validFor": "TimePeriod",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "category": "array<ResourceCategoryRef>",
      "resourceSpecification": "ResourceSpecificationRef",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceCatalog",
    "fields": {
      "category": "array<ResourceCategoryRef>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "description": "string",
      "catalogType": "string",
      "validFor": "TimePeriod",
      "version": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceCategory",
    "fields": {
      "description": "string",
      "name": "string",
      "version": "string",
      "validFor": "TimePeriod",
      "lifecycleStatus": "string",
      "lastUpdate": "string",
      "parentId": "string",
      "isRoot": "boolean",
      "category": "array<ResourceCategoryRef>",
      "resourceSpecification": "array<ResourceSpecificationRef>",
      "resourceCandidate": "array<ResourceCandidateRef>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceFunctionSpecification",
    "fields": {
      "connectionPointSpecification": "array<ConnectionPointSpecificationRef>",
      "connectivitySpecification": "array<ResourceGraphSpecification>",
      "description": "string",
      "version": "string",
      "validFor": "TimePeriod",
      "isBundle": "boolean",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "category": "string",
      "targetResourceSchema": "TargetResourceSchema",
      "featureSpecification": "array<FeatureSpecification>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "resourceSpecCharacteristic": "array<CharacteristicSpecification>",
      "resourceSpecRelationship": "array<ResourceSpecificationRelationship>",
      "intentSpecification": "IntentSpecificationRef",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceGraphSpecification",
    "fields": {
      "name": "string",
      "description": "string",
      "graphSpecificationRelationship": "array<ResourceGraphSpecificationRelationship>",
      "connectionSpecification": "array<ConnectionSpecification>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceSpecification",
    "fields": {
      "description": "string",
      "version": "string",
      "validFor": "TimePeriod",
      "isBundle": "boolean",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "name": "string",
      "category": "string",
      "targetResourceSchema": "TargetResourceSchema",
      "featureSpecification": "array<FeatureSpecification>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "resourceSpecCharacteristic": "array<CharacteristicSpecification>",
      "resourceSpecRelationship": "array<ResourceSpecificationRelationship>",
      "intentSpecification": "IntentSpecificationRef",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceSpecificationRelationship",
    "fields": {
      "relationshipType": "string",
      "role": "string",
      "id": "string",
      "href": "string",
      "name": "string",
      "defaultQuantity": "integer",
      "maximumQuantity": "integer",
      "minimumQuantity": "integer",
      "characteristic": "array<CharacteristicSpecification>",
      "validFor": "TimePeriod",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceUsage",
    "fields": {
      "usageDate": "string",
      "description": "string",
      "usageType": "string",
      "isBundle": "boolean",
      "usageCharacteristic": "array<OneOfCharacteristic>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "resource": "ResourceRef",
      "usageSpecification": "ResourceUsageSpecificationRef",
      "bundledResourceUsage": "array<ResourceUsageRef>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceUsageSpecRelationship",
    "fields": {
      "relationshipType": "string",
      "role": "string",
      "validFor": "TimePeriod",
      "id": "string",
      "href": "string",
      "name": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ResourceUsageSpecification",
    "fields": {
      "name": "string",
      "description": "string",
      "isBundle": "boolean",
      "lastUpdate": "string",
      "lifecycleStatus": "string",
      "version": "string",
      "resourceSpecification": "array<ResourceSpecificationRef>",
      "specCharacteristic": "array<CharacteristicSpecification>",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "bundledResourceUsageSpecification": "array<ResourceUsageSpecificationRef>",
      "resourceUsageSpecRelationship": "array<ResourceUsageSpecRelationship>",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Service",
    "fields": {
      "description": "string",
      "isServiceEnabled": "boolean",
      "hasStarted": "boolean",
      "startMode": "string",
      "isStateful": "boolean",
      "startDate": "string",
      "endDate": "string",
      "serviceOrderItem": "array<RelatedServiceOrderItem>",
      "note": "array<Note>",
      "serviceType": "string",
      "isBundle": "boolean",
      "name": "string",
      "category": "string",
      "feature": "array<Feature>",
      "relatedEntity": "array<RelatedEntityRefOrValue>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "serviceCharacteristic": "array<OneOfCharacteristic>",
      "serviceRelationship": "array<ServiceRelationship>",
      "supportingService": "array<OneOfServiceRefOrValue>",
      "supportingResource": "array<ResourceRef>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "place": "array<RelatedPlaceRefOrValue>",
      "state": "ServiceStateType",
      "operatingStatus": "ServiceOperatingStatusType",
      "serviceSpecification": "ServiceSpecificationRef",
      "serviceDate": "string",
      "intent": "OneOfIntentRefOrValue",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string",
      "x_customStatus": "string",
      "x_serviceType": "string",
      "x_externalId": "string",
      "x_billingAccountId": "string",
      "x_billingAccountName": "string",
      "x_picEmail": "string",
      "x_subscriptionId": "string",
      "x_subscriptionName": "string",
      "x_accountId": "string",
      "x_accountName": "string",
      "x_missingBillingAccount": "boolean",
      "x_missingPicEmail": "boolean",
      "x_missingExternalId": "boolean",
      "x_migratedToHeroku": "boolean",
      "x_migratedData": "boolean",
      "x_has1867Issue": "boolean",
      "x_solutionId": "string",
      "x_solutionName": "string",
      "x_fibreVoiceOE": "boolean",
      "x_fibreFibreOE": "boolean",
      "x_mobileESMSOE": "boolean",
      "x_accessVoiceOE": "boolean",
      "x_parentBundleName": "string",
      "x_replacementServiceId": "string",
      "x_productConfigurationId": "string",
      "x_parentBundleId": "string"
    }
  },
  {
    "name": "ServiceProblem",
    "fields": {
      "affectedLocation": "array<RelatedPlaceRefOrValue>",
      "affectedNumberOfServices": "integer",
      "affectedResource": "array<ResourceRef>",
      "affectedService": "array<ServiceRef>",
      "note": "array<Note>",
      "externalIdentifier": "array<ExternalIdentifier>",
      "name": "string",
      "characteristic": "array<OneOfCharacteristic>",
      "firstAlert": "RelatedEntity",
      "impactImportanceFactor": "string",
      "impactPattern": "ImpactPattern",
      "originatingSystem": "string",
      "parentProblem": "array<ServiceProblemRef>",
      "problemEscalation": "string",
      "relatedEvent": "array<EventRef>",
      "relatedEntity": "array<RelatedEntity>",
      "responsibleParty": "RelatedPartyRefOrPartyRoleRef",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "rootCauseResource": "array<ResourceRef>",
      "rootCauseService": "array<ServiceRef>",
      "resolutionDate": "string",
      "status": "ServiceProblemStateType",
      "statusChangeDate": "string",
      "statusChangeReason": "string",
      "lastUpdate": "string",
      "creationDate": "string",
      "trackingRecord": "array<TrackingRecord>",
      "underlyingAlarm": "array<ResourceAlarmRef>",
      "slaViolation": "array<SLAViolationRef>",
      "troubleTicket": "array<TroubleTicketRef>",
      "underlyingProblem": "array<ServiceProblemRef>",
      "errorMessage": "array<ErrorMessage>",
      "category": "string",
      "description": "string",
      "priority": "integer",
      "reason": "string",
      "originatorParty": "RelatedPartyRefOrPartyRoleRef",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "SettlementAccount",
    "fields": {
      "paymentStatus": "string",
      "billStructure": "BillStructure",
      "paymentPlan": "array<PaymentPlan>",
      "financialAccount": "FinancialAccountRef",
      "defaultPaymentMethod": "PaymentMethodRef",
      "creditLimit": "Money",
      "description": "string",
      "lastUpdate": "string",
      "name": "string",
      "state": "string",
      "accountType": "string",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "taxExemption": "array<TaxExemptionCertificate>",
      "contact": "array<Contact>",
      "accountBalance": "array<AccountBalance>",
      "accountRelationship": "array<AccountRelationship>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "ShoppingCart",
    "fields": {
      "validFor": "TimePeriod",
      "contactMedium": "array<OneOfContactMedium>",
      "cartTotalPrice": "array<CartPrice>",
      "cartItem": "array<CartItem>",
      "relatedParty": "array<RelatedPartyOrPartyRole>",
      "status": "string",
      "creationDate": "string",
      "lastUpdate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Solution1867AccessVoice",
    "fields": {
      "solutionId": "string",
      "solutionName": "string",
      "solutionCreatedDate": "string",
      "solutionDefinitionName": "string",
      "isFibreService": "boolean",
      "isVoiceService": "boolean",
      "hasESMS": "boolean",
      "isESMSService": "boolean",
      "isMobileSolution": "boolean",
      "basketId": "string",
      "basketName": "string",
      "basketStageUI": "string",
      "basketStatus": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Solution1867FibreOnly",
    "fields": {
      "solutionId": "string",
      "solutionName": "string",
      "solutionCreatedDate": "string",
      "solutionDefinitionName": "string",
      "isFibreService": "boolean",
      "isVoiceService": "boolean",
      "hasESMS": "boolean",
      "isESMSService": "boolean",
      "isMobileSolution": "boolean",
      "basketId": "string",
      "basketName": "string",
      "basketStageUI": "string",
      "basketStatus": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Solution1867FibreVoice",
    "fields": {
      "solutionId": "string",
      "solutionName": "string",
      "solutionCreatedDate": "string",
      "solutionDefinitionName": "string",
      "isFibreService": "boolean",
      "isVoiceService": "boolean",
      "hasESMS": "boolean",
      "isESMSService": "boolean",
      "isMobileSolution": "boolean",
      "basketId": "string",
      "basketName": "string",
      "basketStageUI": "string",
      "basketStatus": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Solution1867MobileEsms",
    "fields": {
      "solutionId": "string",
      "solutionName": "string",
      "solutionCreatedDate": "string",
      "solutionDefinitionName": "string",
      "isFibreService": "boolean",
      "isVoiceService": "boolean",
      "hasESMS": "boolean",
      "isESMSService": "boolean",
      "isMobileSolution": "boolean",
      "basketId": "string",
      "basketName": "string",
      "basketStageUI": "string",
      "basketStatus": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "SolutionInfo",
    "fields": {
      "id": "string",
      "href": "string",
      "solutionId": "string",
      "solutionName": "string",
      "externalIdentifier": "string",
      "createdBy": "string",
      "createdDate": "string",
      "migrationStatus": "string",
      "migrationDate": "string",
      "success": "string",
      "message": "string",
      "macdDetails": "string",
      "smServiceStatus": "string",
      "additionalMetadata": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "SolutionMigration",
    "fields": {
      "id": "string",
      "href": "string",
      "solutionId": "string",
      "jobId": "string",
      "status": "string",
      "message": "string",
      "success": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "SolutionPostUpdate",
    "fields": {
      "id": "string",
      "href": "string",
      "solutionId": "string",
      "migrationStatus": "string",
      "jobId": "string",
      "sfdcUpdates": "object",
      "smServiceData": "object",
      "sfdcUpdateStatus": "string",
      "smServiceUpdateStatus": "string",
      "updatedFields": "object",
      "errors": "object",
      "success": "string",
      "message": "string",
      "@type": "string",
      "@baseType": "string"
    }
  },
  {
    "name": "Supplier",
    "fields": {
      "name": "string",
      "description": "string",
      "role": "string",
      "engagedParty": "PartyRef",
      "partyRoleSpecification": "OneOfPartyRoleSpecificationRef",
      "characteristic": "array<OneOfCharacteristic>",
      "account": "array<AccountRef>",
      "agreement": "array<AgreementRef>",
      "contactMedium": "array<OneOfContactMedium>",
      "paymentMethod": "array<PaymentMethodRef>",
      "creditProfile": "array<CreditProfile>",
      "relatedParty": "array<jsonb<RelatedPartyOrPartyRole>>",
      "status": "string",
      "statusReason": "string",
      "validFor": "TimePeriod",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "Task",
    "fields": {
      "id": "string",
      "href": "string",
      "name": "string",
      "description": "string",
      "category": "string",
      "status": "string",
      "statusChangeReason": "string",
      "startDate": "string",
      "completionDate": "string",
      "x_createdById": "string",
      "x_parentJobId": "string",
      "x_methodName": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "TroubleTicket",
    "fields": {
      "name": "string",
      "description": "string",
      "severity": "string",
      "ticketType": "string",
      "attachment": "array<OneOfAttachmentRefOrValue>",
      "channel": "ChannelRef",
      "creationDate": "string",
      "requestedResolutionDate": "string",
      "expectedResolutionDate": "string",
      "resolutionDate": "string",
      "externalIdentifier": "array<ExternalIdentifier>",
      "lastUpdate": "string",
      "note": "array<Note>",
      "priority": "string",
      "relatedEntity": "array<RelatedEntity>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "status": "TroubleTicketStatusType",
      "statusChangeDate": "string",
      "statusChangeReason": "string",
      "statusChangeHistory": "array<StatusChange>",
      "troubleTicketRelationship": "array<TroubleTicketRelationship>",
      "troubleTicketSpecification": "TroubleTicketSpecificationRef",
      "troubleTicketCharacteristic": "array<OneOfCharacteristic>",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "TroubleTicketRelationship",
    "fields": {
      "id": "string",
      "name": "string",
      "relationshipType": "string",
      "href": "string",
      "@referredType": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "TroubleTicketSpecification",
    "fields": {
      "name": "string",
      "description": "string",
      "lifecycleStatus": "string",
      "specCharacteristic": "array<CharacteristicSpecification>",
      "relatedParty": "array<RelatedPartyRefOrPartyRoleRef>",
      "validFor": "TimePeriod",
      "version": "string",
      "creationDate": "string",
      "lastUpdate": "string",
      "href": "string",
      "id": "string",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "UnAckAlarm",
    "fields": {
      "id": "string",
      "href": "string",
      "state": "string",
      "ackSystemId": "string",
      "ackUserId": "string",
      "ackTime": "string",
      "alarmPattern": "array<OneOfAlarmRefOrValue>",
      "unAckedAlarm": "array<OneOfAlarmRefOrValue>",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  },
  {
    "name": "UnGroupAlarm",
    "fields": {
      "id": "string",
      "href": "string",
      "state": "string",
      "sourceSystemId": "string",
      "alarmChangedTime": "string",
      "parentAlarm": "OneOfAlarmRefOrValue",
      "correlatedAlarm": "array<OneOfAlarmRefOrValue>",
      "unGroupedAlarm": "array<OneOfAlarmRefOrValue>",
      "@type": "string",
      "@baseType": "string",
      "@schemaLocation": "string"
    }
  }
];
