/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event.
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase.
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service.
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */
import { delay, HttpResponse, http } from 'msw';
import type { HubFVOBody, HubResponse } from '.././types';

const staticHubData: readonly HubResponse[] = [
  {
    id: 'hub-shopping-cart-001',
    callback: 'https://api.example.com/webhooks/shopping-cart-events',
    query: 'eventType=ShoppingCartCreateEvent',
    '@type': 'Hub',
    '@baseType': undefined,
    '@schemaLocation': undefined,
    href: undefined,
  },
  {
    id: 'hub-shopping-cart-002',
    callback: 'https://api.example.com/webhooks/cart-state-changes',
    query: 'eventType=ShoppingCartStateChangeEvent',
    '@type': 'Hub',
    '@baseType': undefined,
    '@schemaLocation': undefined,
    href: undefined,
  },
] as const;

let storeHubData: HubResponse[] = [...staticHubData];

export const getCreateHubMockHandler = (
  overrideResponse?:
    | HubResponse
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<HubResponse> | HubResponse),
) => {
  return http.post('*/hub', async (info) => {
    await delay(1000);
    if (overrideResponse !== undefined) {
      return new HttpResponse(
        JSON.stringify(
          typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse,
        ),
        {
          status: 201,
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );
    }
    const body = (await info.request.json()) as HubFVOBody;
    const newHub: HubResponse = {
      id: crypto.randomUUID(),
      callback: body.callback ?? 'https://api.example.com/webhooks/default',
      query: body.query,
      '@type': 'Hub',
      '@baseType': body['@baseType'],
      '@schemaLocation': body['@schemaLocation'],
      href: undefined,
    };
    storeHubData.push(newHub);
    return new HttpResponse(JSON.stringify(newHub), {
      status: 201,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getHubDeleteMockHandler = () => {
  return http.delete('*/hub/:id', async (info) => {
    await delay(1000);
    const id = info.params.id as string;
    storeHubData = storeHubData.filter((item) => item.id !== id);
    return new HttpResponse(null, {
      status: 204,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getAllMocks = () => [
  getCreateHubMockHandler(),
  getHubDeleteMockHandler(),
];
