/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event.
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase.
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service.
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */

import { tmfFetcher } from '../../tmf-fetcher';
import type {
  ShoppingCartAttributeValueChangeEventBody,
  ShoppingCartCreateEventBody,
  ShoppingCartDeleteEventBody,
} from '.././types';

/**
 * Example of a client listener for receiving the notification ShoppingCartAttributeValueChangeEvent
 * @summary Client listener for entity ShoppingCartAttributeValueChangeEvent
 */
export type shoppingCartAttributeValueChangeEventResponse = {
  data: void;
  status: number;
};

export const getShoppingCartAttributeValueChangeEventUrl = () => {
  return `/listener/shoppingCartAttributeValueChangeEvent`;
};

export const shoppingCartAttributeValueChangeEvent = async (
  shoppingCartAttributeValueChangeEventBody: ShoppingCartAttributeValueChangeEventBody,
  options?: RequestInit,
): Promise<shoppingCartAttributeValueChangeEventResponse> => {
  return tmfFetcher<Promise<shoppingCartAttributeValueChangeEventResponse>>(
    getShoppingCartAttributeValueChangeEventUrl(),
    {
      ...options,
      method: 'POST',
      body: JSON.stringify(shoppingCartAttributeValueChangeEventBody),
    },
  );
};

/**
 * Example of a client listener for receiving the notification ShoppingCartCreateEvent
 * @summary Client listener for entity ShoppingCartCreateEvent
 */
export type shoppingCartCreateEventResponse = {
  data: void;
  status: number;
};

export const getShoppingCartCreateEventUrl = () => {
  return `/listener/shoppingCartCreateEvent`;
};

export const shoppingCartCreateEvent = async (
  shoppingCartCreateEventBody: ShoppingCartCreateEventBody,
  options?: RequestInit,
): Promise<shoppingCartCreateEventResponse> => {
  return tmfFetcher<Promise<shoppingCartCreateEventResponse>>(
    getShoppingCartCreateEventUrl(),
    {
      ...options,
      method: 'POST',
      body: JSON.stringify(shoppingCartCreateEventBody),
    },
  );
};

/**
 * Example of a client listener for receiving the notification ShoppingCartDeleteEvent
 * @summary Client listener for entity ShoppingCartDeleteEvent
 */
export type shoppingCartDeleteEventResponse = {
  data: void;
  status: number;
};

export const getShoppingCartDeleteEventUrl = () => {
  return `/listener/shoppingCartDeleteEvent`;
};

export const shoppingCartDeleteEvent = async (
  shoppingCartDeleteEventBody: ShoppingCartDeleteEventBody,
  options?: RequestInit,
): Promise<shoppingCartDeleteEventResponse> => {
  return tmfFetcher<Promise<shoppingCartDeleteEventResponse>>(
    getShoppingCartDeleteEventUrl(),
    {
      ...options,
      method: 'POST',
      body: JSON.stringify(shoppingCartDeleteEventBody),
    },
  );
};
