/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event.
Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase.
Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service.
Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.


Copyright © TM Forum 2022. All Rights Reserved



 * OpenAPI spec version: 5.0.0
 */

import { tmfFetcher } from '../../tmf-fetcher';
import type {
  CreateShoppingCartParams,
  ListShoppingCartParams,
  N200ShoppingCartArrayResponse,
  N200ShoppingCartGetResponse,
  N200ShoppingCartPatchResponse,
  N201ShoppingCartResponse,
  N202Response,
  N204Response,
  PatchShoppingCartParams,
  RetrieveShoppingCartParams,
  ShoppingCartFVOBody,
  ShoppingCartMVOBody,
} from '.././types';

/**
 * List or find ShoppingCart objects
 * @summary List or find ShoppingCart objects
 */
export type listShoppingCartResponse = {
  data: N200ShoppingCartArrayResponse;
  status: number;
};

export const getListShoppingCartUrl = (params?: ListShoppingCartParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === null) {
      normalizedParams.append(key, 'null');
    } else if (value !== undefined) {
      normalizedParams.append(key, value.toString());
    }
  });

  return `/shoppingCart?${normalizedParams.toString()}`;
};

export const listShoppingCart = async (
  params?: ListShoppingCartParams,
  options?: RequestInit,
): Promise<listShoppingCartResponse> => {
  return tmfFetcher<Promise<listShoppingCartResponse>>(
    getListShoppingCartUrl(params),
    {
      ...options,
      method: 'GET',
    },
  );
};

/**
 * This operation creates a ShoppingCart entity.
 * @summary Creates a ShoppingCart
 */
export type createShoppingCartResponse = {
  data: N201ShoppingCartResponse | void;
  status: number;
};

export const getCreateShoppingCartUrl = (params?: CreateShoppingCartParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === null) {
      normalizedParams.append(key, 'null');
    } else if (value !== undefined) {
      normalizedParams.append(key, value.toString());
    }
  });

  return `/shoppingCart?${normalizedParams.toString()}`;
};

export const createShoppingCart = async (
  shoppingCartFVOBody: ShoppingCartFVOBody,
  params?: CreateShoppingCartParams,
  options?: RequestInit,
): Promise<createShoppingCartResponse> => {
  return tmfFetcher<Promise<createShoppingCartResponse>>(
    getCreateShoppingCartUrl(params),
    {
      ...options,
      method: 'POST',
      body: JSON.stringify(shoppingCartFVOBody),
    },
  );
};

/**
 * This operation retrieves a ShoppingCart entity. Attribute selection enabled for all first level attributes.
 * @summary Retrieves a ShoppingCart by ID
 */
export type retrieveShoppingCartResponse = {
  data: N200ShoppingCartGetResponse;
  status: number;
};

export const getRetrieveShoppingCartUrl = (
  id: string,
  params?: RetrieveShoppingCartParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === null) {
      normalizedParams.append(key, 'null');
    } else if (value !== undefined) {
      normalizedParams.append(key, value.toString());
    }
  });

  return `/shoppingCart/${id}?${normalizedParams.toString()}`;
};

export const retrieveShoppingCart = async (
  id: string,
  params?: RetrieveShoppingCartParams,
  options?: RequestInit,
): Promise<retrieveShoppingCartResponse> => {
  return tmfFetcher<Promise<retrieveShoppingCartResponse>>(
    getRetrieveShoppingCartUrl(id, params),
    {
      ...options,
      method: 'GET',
    },
  );
};

/**
 * This operation updates partially a ShoppingCart entity.
 * @summary Updates partially a ShoppingCart
 */
export type patchShoppingCartResponse = {
  data: N200ShoppingCartPatchResponse | void;
  status: number;
};

export const getPatchShoppingCartUrl = (
  id: string,
  params?: PatchShoppingCartParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value === null) {
      normalizedParams.append(key, 'null');
    } else if (value !== undefined) {
      normalizedParams.append(key, value.toString());
    }
  });

  return `/shoppingCart/${id}?${normalizedParams.toString()}`;
};

export const patchShoppingCart = async (
  id: string,
  shoppingCartMVOBody: ShoppingCartMVOBody,
  params?: PatchShoppingCartParams,
  options?: RequestInit,
): Promise<patchShoppingCartResponse> => {
  return tmfFetcher<Promise<patchShoppingCartResponse>>(
    getPatchShoppingCartUrl(id, params),
    {
      ...options,
      method: 'PATCH',
      body: JSON.stringify(shoppingCartMVOBody),
    },
  );
};

/**
 * This operation deletes a ShoppingCart entity.
 * @summary Deletes a ShoppingCart
 */
export type deleteShoppingCartResponse = {
  data: N202Response | N204Response;
  status: number;
};

export const getDeleteShoppingCartUrl = (id: string) => {
  return `/shoppingCart/${id}`;
};

export const deleteShoppingCart = async (
  id: string,
  options?: RequestInit,
): Promise<deleteShoppingCartResponse> => {
  return tmfFetcher<Promise<deleteShoppingCartResponse>>(
    getDeleteShoppingCartUrl(id),
    {
      ...options,
      method: 'DELETE',
    },
  );
};
