/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Shopping Cart
 * **Test TMF API Reference : TMF - 663 Shopping Cart**
 * The Shoppoing Cart API provides a standardized mechanism for the management of shopping carts. Including creation, update, retrieval, deletion and notification of event.
 * Shopping Cart entity is used for the temporarily selection and reservation of product offerings in e-commerce and retail purchase.
 * Shopping cart supports purchase of both tangible and intangible goods and service (e.g. handset, telecom network service). The charge includes a one-off fee such as fee for handset and recurring fee such as fee of a network service.
 * Shopping Cart contains list of cart items, a reference to party or party role (e.g. customer) or contact medium in case of unknown customer, In addition the calculated items total price including promotions.
 *
 *
 * Copyright © TM Forum 2022. All Rights Reserved
 *
 *
 *
 * OpenAPI spec version: 5.0.0
 */
import { delay, HttpResponse, http } from 'msw';
import { applyPagination } from '../../mock-utils';
import type {
  N200ShoppingCartArrayResponse,
  N200ShoppingCartGetResponse,
  N200ShoppingCartPatchResponse,
  N201ShoppingCartResponse,
  ShoppingCartFVOBody,
  ShoppingCartMVOBody,
} from '.././types';

const staticShoppingCartData: readonly N200ShoppingCartArrayResponse[number][] =
  [
    {
      id: 'shopping-cart-001',
      status: 'active',
      '@type': 'ShoppingCart',
      '@baseType': undefined,
      '@schemaLocation': undefined,
      href: undefined,
    },
    {
      id: 'shopping-cart-002',
      status: 'active',
      '@type': 'ShoppingCart',
      '@baseType': undefined,
      '@schemaLocation': undefined,
      href: undefined,
    },
    {
      id: 'shopping-cart-003',
      status: 'abandoned',
      '@type': 'ShoppingCart',
      '@baseType': undefined,
      '@schemaLocation': undefined,
      href: undefined,
    },
  ] as unknown as readonly N200ShoppingCartArrayResponse[number][];

let storeShoppingCartData: N200ShoppingCartArrayResponse = [
  ...staticShoppingCartData,
] as unknown as N200ShoppingCartArrayResponse;

export const getListShoppingCartMockHandler = (
  overrideResponse?:
    | N200ShoppingCartArrayResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) =>
        | Promise<N200ShoppingCartArrayResponse>
        | N200ShoppingCartArrayResponse),
) => {
  return http.get('*/shoppingCart', async (info) => {
    await delay(1000);
    if (overrideResponse !== undefined) {
      return new HttpResponse(
        JSON.stringify(
          typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse,
        ),
        {
          status: 200,
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );
    }
    const url = new URL(info.request.url);
    const limitParam: string | null = url.searchParams.get('limit');
    const offsetParam: string | null = url.searchParams.get('offset');
    const limit: number | undefined = limitParam
      ? Number.parseInt(limitParam, 10)
      : undefined;
    const offset: number | undefined = offsetParam
      ? Number.parseInt(offsetParam, 10)
      : undefined;
    const paginatedData: N200ShoppingCartArrayResponse = applyPagination(
      storeShoppingCartData,
      limit,
      offset,
    );
    return new HttpResponse(JSON.stringify(paginatedData), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getCreateShoppingCartMockHandler = (
  overrideResponse?:
    | N201ShoppingCartResponse
    | undefined
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) =>
        | Promise<N201ShoppingCartResponse | undefined>
        | N201ShoppingCartResponse
        | undefined),
) => {
  return http.post('*/shoppingCart', async (info) => {
    await delay(1000);
    if (overrideResponse !== undefined) {
      return new HttpResponse(
        JSON.stringify(
          typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse,
        ),
        {
          status: 201,
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );
    }
    const body = (await info.request.json()) as ShoppingCartFVOBody;
    const newShoppingCart: N201ShoppingCartResponse = {
      id: crypto.randomUUID(),
      status: 'active',
      '@type': 'ShoppingCart',
      '@baseType': body['@baseType'],
      '@schemaLocation': body['@schemaLocation'],
      href: undefined,
    } as unknown as N201ShoppingCartResponse;
    storeShoppingCartData.push(newShoppingCart);
    return new HttpResponse(JSON.stringify(newShoppingCart), {
      status: 201,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getRetrieveShoppingCartMockHandler = (
  overrideResponse?:
    | N200ShoppingCartGetResponse
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<N200ShoppingCartGetResponse> | N200ShoppingCartGetResponse),
) => {
  return http.get('*/shoppingCart/:id', async (info) => {
    await delay(1000);
    if (overrideResponse !== undefined) {
      return new HttpResponse(
        JSON.stringify(
          typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse,
        ),
        {
          status: 200,
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );
    }
    const id = info.params.id as string;
    const storeItem = (
      storeShoppingCartData as unknown as Array<{ id?: string }>
    ).find((item) => item.id === id);
    const staticItem = (
      staticShoppingCartData as unknown as Array<{ id?: string }>
    ).find((item) => item.id === id);
    const shoppingCart: N200ShoppingCartGetResponse | undefined = (storeItem ??
      staticItem) as N200ShoppingCartGetResponse | undefined;
    if (shoppingCart === undefined) {
      return new HttpResponse(null, {
        status: 404,
        headers: {
          'Content-Type': 'application/json',
        },
      });
    }
    return new HttpResponse(JSON.stringify(shoppingCart), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getPatchShoppingCartMockHandler = (
  overrideResponse?:
    | N200ShoppingCartPatchResponse
    | undefined
    | ((
        info: Parameters<Parameters<typeof http.patch>[1]>[0],
      ) =>
        | Promise<N200ShoppingCartPatchResponse | undefined>
        | N200ShoppingCartPatchResponse
        | undefined),
) => {
  return http.patch('*/shoppingCart/:id', async (info) => {
    await delay(1000);
    if (overrideResponse !== undefined) {
      return new HttpResponse(
        JSON.stringify(
          typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse,
        ),
        {
          status: 200,
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );
    }
    const id = info.params.id as string;
    const body = (await info.request.json()) as ShoppingCartMVOBody;
    const index: number = (
      storeShoppingCartData as unknown as Array<{ id?: string }>
    ).findIndex((item) => item.id === id);
    if (index === -1) {
      return new HttpResponse(null, {
        status: 404,
        headers: {
          'Content-Type': 'application/json',
        },
      });
    }
    const updatedShoppingCart: N200ShoppingCartPatchResponse = {
      ...(storeShoppingCartData[index] as unknown as Record<string, unknown>),
      ...(typeof body === 'object' && 'status' in body ? body : {}),
      '@type': 'ShoppingCart',
    } as unknown as N200ShoppingCartPatchResponse;
    storeShoppingCartData[index] =
      updatedShoppingCart as unknown as N200ShoppingCartArrayResponse[number];
    return new HttpResponse(JSON.stringify(updatedShoppingCart), {
      status: 200,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getDeleteShoppingCartMockHandler = () => {
  return http.delete('*/shoppingCart/:id', async (info) => {
    await delay(1000);
    const id = info.params.id as string;
    storeShoppingCartData = (
      storeShoppingCartData as unknown as Array<{ id?: string }>
    ).filter(
      (item) => item.id !== id,
    ) as unknown as N200ShoppingCartArrayResponse;
    return new HttpResponse(null, {
      status: 202,
      headers: {
        'Content-Type': 'application/json',
      },
    });
  });
};

export const getAllMocks = () => [
  getListShoppingCartMockHandler(),
  getCreateShoppingCartMockHandler(),
  getRetrieveShoppingCartMockHandler(),
  getPatchShoppingCartMockHandler(),
  getDeleteShoppingCartMockHandler(),
];
